printWidth: 95
tabWidth: 4
useTabs: false
semi: false
singleQuote: true
trailingComma: 'es5'
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: 'avoid'
proseWrap: 'never'
trailingCommaPHP: false
braceStyle: 'psr-2'
overrides:
    - files: '*.vue'
      options:
          printWidth: 95
      parser: 'vue'
